### ISSUE TITLE
On est toujours en 3.1.9-SNAPSHOT

### ISSUE THREAD

**Issue by adriens** [DSI-Ville-Noumea/gasel#4]
... dès qu'on est sur une vraie version, on taggera et planifier la déploiement.
Merci.

**Comment by adriens** [comment]
` De : moussin [mailto:notifications@github.com]
Envoyé : mercredi 2 décembre 2015 16:17
À : DSI-Ville-Noumea/gasel
Cc : BOURDIL luc
Objet : Re: [gasel] Réponse à la demande de MER (#5)

Bonjour,

Pour taguer, il vous suffit d'effectuer un "git tag nomTag
8edb7519154dfdae98515e5e3d36b44aa4c674c0".
Le numéro de commit ci dessus correspond au dernier commit de la version
3.1.9.
Les commits suivants font partis de la 3.1.10. Ils sont mis en évidence
dans la pull request "version-3.1.9-SNAPSHOT#3" qui résume l'évolution
de 3.1.9 à 3.1.10.

Guillaume`

je regarde ça de suite.

**Comment by adriens** [comment]
fetch en cours...

**Comment by adriens** [comment]
après le clone :
cd gasel
git tag GASEL-3.1.9 8edb7519154dfdae98515e5e3d36b44aa4c674c0
git push --tags

me donne :
To https://adriens@github.com/DSI-Ville-Noumea/gasel.git
- [new tag]         GASEL-3.1.9 -> GASEL-3.1.9

... mais quand je vais sur https://github.com/DSI-Ville-Noumea/gasel/blob/GASEL-3.1.9/pom.xml

le pom est toujours en `3.1.9-SNAPSHOT` ... j'ai zappé un truc ? ou bien ?

**Comment by mcluseau** [comment]
Hello, redmine 20011#note-6
